chore: test Makefile with wf

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -11,6 +11,7 @@ on:
 env:
   PACKAGE_NAME: "profiling-tools"
   OWNER: "TheNewThinkTank"
+  # TAP_NAME: "<# >"  # for homebrew publishing
 
 jobs:
   details:
@@ -24,14 +25,36 @@ jobs:
 
       - name: Extract tag and Details
         id: release
-        run: make extract-version
+        run: |
+          if [ "${{ github.ref_type }}" = "tag" ]; then
+            TAG_NAME=${GITHUB_REF#refs/tags/}
+            NEW_VERSION=$(echo $TAG_NAME | awk -F'-' '{print $1}')
+            SUFFIX=$(echo $TAG_NAME | grep -oP '[a-z]+[0-9]+' || echo "")
+            echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
+            echo "suffix=$SUFFIX" >> "$GITHUB_OUTPUT"
+            echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
+            echo "Version is $NEW_VERSION"
+            echo "Suffix is $SUFFIX"
+            echo "Tag name is $TAG_NAME"
+          else
+            echo "No tag found"
+            exit 1
+          fi
 
   check_pypi:
     needs: details
     runs-on: ubuntu-latest
     steps:
       - name: Fetch information from PyPI
-        run: make check-pypi-version
+        run: |
+          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
+          latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
+          if [ -z "$latest_previous_version" ]; then
+            echo "Package not found on PyPI."
+            latest_previous_version="0.0.0"
+          fi
+          echo "Latest version on PyPI: $latest_previous_version"
+          echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV
 
       - name: Compare versions and exit if not newer
         run: |
@@ -49,10 +72,28 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: Set up Python and dependencies
-        run: make setup-python
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.12"
+
+      - name: Install Poetry
+        run: |
+          curl -sSL https://install.python-poetry.org | python3 -
+          echo "$HOME/.local/bin" >> $GITHUB_PATH
+
+      - name: Set project version with Poetry
+        run: |
+          poetry version ${{ needs.details.outputs.new_version }}
+
+      - name: Install dependencies
+        run: poetry install --sync --no-interaction
+
       - name: Build source and wheel distribution
-        run: make build-package
+        run: |
+          poetry build
+
       - name: Upload artifacts
         uses: actions/upload-artifact@v3
         with:
@@ -63,12 +104,17 @@ jobs:
     name: Upload release to PyPI
     needs: [setup_and_build, details]
     runs-on: ubuntu-latest
+    environment:
+      name: release
+    permissions:
+      id-token: write
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: dist
           path: dist/
+
       - name: Publish distribution to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
 
@@ -76,15 +122,47 @@ jobs:
     name: Create GitHub Release
     needs: [setup_and_build, details]
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: dist
           path: dist/
+
       - name: Create GitHub Release
+        id: create_release
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
           gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
+
+#   bump_homebrew_formula:
+#     name: Dispatch event to Repo B
+#     needs: [details, github_release, pypi_publish]
+#     runs-on: ubuntu-latest
+#     environment:
+#       name: release
+#     steps:
+#       - name: Dispatch Repository Dispatch event
+#         uses: peter-evans/repository-dispatch@v2
+#         with:
+#           token: ${{ secrets.BREW_TAP_TOKEN }}
+#           repository: ${{ env.OWNER }}/{{ env.#  }}
+#           event-type: "update-formula"
+#           client-payload: |-
+#             { 
+#               "formula_version": "${{env.FORMULA_VERSION}}", 
+#               "formula_url": "${{ env.FORMULA_URL }}", 
+#               "formula_name": "${{ env.FORMULA_NAME }}"
+#             }
+#         env:
+#           FORMULA_VERSION: ${{ needs.details.outputs.new_version }}
+#           FORMULA_NAME: ${{ env.PACKAGE_NAME }}
+#           FORMULA_URL: https://github.com/${{env.OWNER}}/${{env.PACKAGE_NAME}}/releases/download/${{ needs.details.outputs.new_version }}/${{env.PACKAGE_NAME}}-${{ needs.details.outputs.new_version }}.tar.gz
